Button_yellow  = Button(root,text="Grid:yellow",command=grid_yellow,bg="#FFFF00").grid(row=0,column=1)  
Button_blue  = Button(root,text="Grid:blue",command=grid_blue,bg="#0000FF").grid(row=0,column=2)  
Button_red  = Button(root,text="Grid:RED",command=grid_red,bg="#FF0000").grid(row=0,column=3)  
Button_white  = Button(root,text="Grid:White",command=grid_white,bg="#FFFFFF").grid(row=0,column=6)  
Button_green  = Button(root,text="Grid:Green",command=grid_green,bg="#00FF00").grid(row=0,column=4)  
Button_orange  = Button(root,text="Grid:Orange",command=grid_orange,bg="#FFA500").grid(row=0,column=5)
Button_sol  = Button(root,text="Get solution ->",command=solve,bg="#00a0b0").grid(row=0,column=67)
Button_send  = Button(root,text="Send to arduino ->",command=send_arduino,bg="#006069").grid(row=0,column=68)
Button_command  = Button(root,text="test_code -> terminal",command=test,bg="#26c2e3").grid(row=0,column=66)
Button_command2  = Button(root,text="convert first -> ",command=convert_hex,bg="#006069").grid(row=0,column=65)
